### ISSUE TITLE
declaration-colon-space-after should be set to always-single-line

### ISSUE THREAD

**Issue by chris-fran** [prettier/stylelint-config-prettier#27]
```scss
.foo {
  &__bar {
    grid-template-columns:    // <---- makes no sense having an space after this colon
      repeat(#{$some-long-variable-name - 1}, [item] min-content [spacer] minmax(8px, 32px))
      [item] min-content;
  }
}
```

Does this make any sense or am I missing something?
