### ISSUE TITLE
This is turning off too much I think

### ISSUE THREAD

**Issue by ThiefMaster** [prettier/stylelint-config-prettier#96]
For example, by disabling the default for `rule-empty-line-before` (coming from stylelint-config-standard), this CSS is accepted:

```css
.a {
  color: #fff;
}
.b {
  color: #000;
}
```

But prettier has no opinion on this, so a useful rule for readability gets disabled, which would otherwise reformat to this:

```css
.a {
  color: #fff;
}

.b {
  color: #000;
}
```
